name: Check build NPF Web Extension app (CI)

on:
  pull_request:
    types: [opened]
    branches:
      - "main"
  push: # Do not run this on main branch because we have another workflow for the release
    branches:
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install packages
        run: npm install

      - name: run coverage tests
        run: npm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
