name: Publish python package to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Building package
      - name: Building package
        working-directory: ./python/
        run: python3 -m pip install --upgrade build && python3 -m build --sdist --sdist-dir ../dist/

      # Publishing to pypi
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
