name: Build and Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Getting package version
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      # Dependencies
      - name: Install Dependencies
        run: npm install

      # Building
      - name: Build
        run: npm run build

      # Zipping build dir
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release-${{ steps.package-version.outputs.current-version }}.zip build

      # Releasing
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }}
          body: Automated release from pull request ${{ github.event.pull_request.number }}
          artifacts: "release-${{ steps.package-version.outputs.current-version }}.zip"
          allowUpdates: true

      # Uplading release
      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ steps.package-version.outputs.current-version }}
          path: build/
          if-no-files-found: error
      
      # Building package for pypi
      - name: Building package
        run: python3 -m pip install --upgrade build && python3 -m build

      # Publishing to pypi
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
