name: Build and Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Get version label
      - name: Get Version Label
        id: version
        run: "echo ::set-env name=VERSION_LABEL::$(curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels | jq -r '.[] | select(.name | startswith('v')) | .name')"

      
      # Dependencies
      - name: Install Dependencies
        run: npm install
        
      # Building
      - name: Build
        run: npm run build
        
      # Releasing
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_LABEL }}
          release_name: Release ${{ env.VERSION_LABEL }}
          body: Automated release from pull request ${{ github.event.pull_request.number }}
          draft: false
          prerelease: false
        
      # Uplading release
      - name: Upload Release Assets
        uses: actions/upload-artifact@v2
        with:
          name: npf-web-extension-build
          path: build/
          if-no-files-found: error
