name: Build and Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Getting package version
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      
      # Node modules cache
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      # Dependencies
      - name: Install Dependencies
        run: npm install

      # Building
      - name: Build
        run: npm run deploy

      # Zipping build dir
      # - uses: montudor/action-zip@v1
      #   with:
      #     args: zip -qq -r release-${{ steps.package-version.outputs.current-version }}.zip build

      # Releasing
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }}
          body: Automated release from pull request ${{ github.event.pull_request.number }}
          # artifacts: "release-${{ steps.package-version.outputs.current-version }}.zip"
          artifacts: "build/index.html"
          allowUpdates: true
          token: ${{ secrets.PAT }}

      # Uploading release
      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: build/index.html
          if-no-files-found: error
      
      # Checkout last version
      - uses: actions/checkout@v3
        with:
          ref: v${{ steps.package-version.outputs.current-version }}
      
      # Download release after checkout
      - uses: actions/download-artifact@v3
        with:
          name: index.html
          path: python_src/npf_web_extension/template.py

      # Building package for pypi
      - name: Building package
        run: python3 -m pip install --upgrade build && python3 -m build
      
      # Debug
      - name: Debug
        run: ls -la python_src/npf_web_extension/

      # Publishing to pypi
      # - name: Publish package
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     verbose: true
      #     verify-metadata: false # The twine check version used is not updated and still uses the legacy which doesn't handle gh markdown properly 
      #     password: ${{ secrets.PYPI_API_TOKEN }}
