name: Build and Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} # Enable branch protection bypass

      # Getting package version
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      # Node modules cache
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      # Dependencies
      - name: Install Dependencies
        run: npm install

      # Building
      - name: Build
        run: npm run deploy

      # Zipping build dir
      # - uses: montudor/action-zip@v1
      #   with:
      #     args: zip -qq -r release-${{ steps.package-version.outputs.current-version }}.zip build

      # Uploading template.html to repo
      - name: Upload template.html to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "python_src/npf_web_extension/template.html"
          commit: --signoff
          default_author: github_actions
          fetch: false
          pathspec_error_handling: exitImmediately

      # Releasing
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }}
          body: Automated release from pull request ${{ github.event.pull_request.number }}
          # artifacts: "release-${{ steps.package-version.outputs.current-version }}.zip"
          artifacts: "build/index.html"
          allowUpdates: true
          token: ${{ secrets.PAT }}

      # Uploading release
      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: template.html
          path: build/index.html
          if-no-files-found: error

      # Checkout last version
      - uses: actions/checkout@v3
        with:
          ref: v${{ steps.package-version.outputs.current-version }}

      # Building package for pypi
      - name: Building package
        run: python3 -m pip install --upgrade build && python3 -m build

      # Debug
      - name: Debug
        run: ls -la python_src/npf_web_extension/

      # Upload package artifact
      - name: Upload PyPi Package artifact
        uses: actions/upload-artifact@v3
        with:
          name: v${{ steps.package-version.outputs.current-version }}
          path: dist
          if-no-files-found: error

      # Publishing to pypi
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          verify-metadata: false # the check is bugged somehow inside github env but it is uploaded properly on pypi
          password: ${{ secrets.PYPI_API_TOKEN }}
